# Generated by Django 6.0.8 on 2026-09-20 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='razão social')),
                ('fantasia', models.CharField(blank=True, max_length=255, verbose_name='nome fantasia')),
                ('cnpj', models.CharField(help_text='Só dígitos — a máscara é da tela (ver apps/fornecedores/documentos.py).', max_length=14, verbose_name='CNPJ')),
                ('porte', models.CharField(choices=[('mei', 'MEI'), ('me', 'Microempresa (ME)'), ('epp', 'Empresa de pequeno porte (EPP)'), ('demais', 'Demais')], default='demais', max_length=8, verbose_name='porte')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=40, verbose_name='inscrição estadual')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=40, verbose_name='inscrição municipal')),
                ('cnae_principal', models.CharField(blank=True, help_text='É o que decide se esta empresa pode disputar um objeto ou não.', max_length=10, verbose_name='CNAE principal')),
                ('cep', models.CharField(blank=True, max_length=8, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=255, verbose_name='logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('complemento', models.CharField(blank=True, max_length=120, verbose_name='complemento')),
                ('bairro', models.CharField(blank=True, max_length=120, verbose_name='bairro')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('cidade', models.CharField(blank=True, max_length=120, verbose_name='cidade')),
                ('responsavel_legal', models.CharField(blank=True, help_text='Quem assina proposta e contrato — é o nome que entra nas declarações geradas.', max_length=150, verbose_name='responsável legal')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('padrao', models.BooleanField(default=False, help_text='A que já vem escolhida na proposta. Uma por tenant.', verbose_name='empresa padrão')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='cadastrada em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_cadastradas', to=settings.AUTH_USER_MODEL, verbose_name='cadastrada por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'cnpj'), name='empresa_cnpj_unico_por_tenant'), models.UniqueConstraint(condition=models.Q(('padrao', True)), fields=('tenant',), name='empresa_padrao_unica_por_tenant')],
            },
        ),
    ]
