# Generated by Django 6.0.8 on 2026-10-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_nome_do_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='agencia',
            field=models.CharField(blank=True, max_length=20, verbose_name='agência'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='banco',
            field=models.CharField(blank=True, max_length=80, verbose_name='banco'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='conta',
            field=models.CharField(blank=True, max_length=30, verbose_name='conta-corrente'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='responsavel_cpf',
            field=models.CharField(blank=True, max_length=14, verbose_name='CPF do responsável'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='responsavel_qualificacao',
            field=models.TextField(blank=True, help_text='Nacionalidade, estado civil, profissão, endereço — o parágrafo do representante na proposta comercial.', verbose_name='qualificação do responsável'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='responsavel_rg',
            field=models.CharField(blank=True, max_length=40, verbose_name='RG do responsável'),
        ),
    ]
