# Generated by Django 6.0.8 on 2026-08-26 13:47
#
# TrigramExtension() inserida manualmente antes do CreateModel — os índices
# GIN com opclass `gin_trgm_ops` abaixo exigem `CREATE EXTENSION pg_trgm`
# antes de existir, e o makemigrations não detecta essa dependência sozinho.
# Precisa que o usuário do Postgres (`licita`) tenha privilégio para criar
# extensão — ver docs/DOMINIO.md e k8s/README.md.

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name='Pdm',
            fields=[
                ('codigo_pdm', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_pdm', models.CharField(max_length=255)),
                ('nome_normalizado', models.CharField(max_length=255)),
                ('codigo_classe', models.IntegerField(blank=True, db_index=True, null=True)),
                ('nome_classe', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_classe_normalizado', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_grupo', models.IntegerField(blank=True, db_index=True, null=True)),
                ('nome_grupo', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_grupo_normalizado', models.CharField(blank=True, max_length=255, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PDM',
                'verbose_name_plural': 'PDMs',
                'ordering': ['nome_pdm'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['nome_normalizado'], name='pdm_nome_trgm', opclasses=['gin_trgm_ops']), django.contrib.postgres.indexes.GinIndex(fields=['nome_grupo_normalizado'], name='pdm_grupo_trgm', opclasses=['gin_trgm_ops']), django.contrib.postgres.indexes.GinIndex(fields=['nome_classe_normalizado'], name='pdm_classe_trgm', opclasses=['gin_trgm_ops'])],
            },
        ),
    ]
