# Generated by Django 6.0.8 on 2026-10-04 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cotador', '0004_nome_do_autor'),
        ('fornecedores', '0002_nome_do_autor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('nome_normalizado', models.CharField(editable=False, help_text='Caixa alta e sem acento — é por ele que se detecta duplicata.', max_length=150, verbose_name='nome normalizado')),
                ('criado_por_nome', models.CharField(blank=True, max_length=150, verbose_name='cadastrado por (nome)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='cadastrado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabricantes_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='cadastrado por')),
                ('fornecedores', models.ManyToManyField(blank=True, help_text='Afinidade: quem vende este fabricante (e todas as marcas e modelos dele).', related_name='fabricantes', to='fornecedores.fornecedor', verbose_name='fornecedores')),
            ],
            options={
                'verbose_name': 'fabricante',
                'verbose_name_plural': 'fabricantes',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('nome_normalizado', models.CharField(editable=False, help_text='Caixa alta e sem acento — é por ele que se detecta duplicata.', max_length=150, verbose_name='nome normalizado')),
                ('criado_por_nome', models.CharField(blank=True, max_length=150, verbose_name='cadastrado por (nome)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='cadastrado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcas_cadastradas', to=settings.AUTH_USER_MODEL, verbose_name='cadastrado por')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcas', to='produtos.fabricante', verbose_name='fabricante')),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('nome_normalizado', models.CharField(editable=False, help_text='Caixa alta e sem acento — é por ele que se detecta duplicata.', max_length=150, verbose_name='nome normalizado')),
                ('criado_por_nome', models.CharField(blank=True, max_length=150, verbose_name='cadastrado por (nome)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='cadastrado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelos_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='cadastrado por')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='produtos.marca', verbose_name='marca')),
            ],
            options={
                'verbose_name': 'modelo',
                'verbose_name_plural': 'modelos',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrecoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='custo do produto (un.)')),
                ('registrado_por_nome', models.CharField(blank=True, max_length=150, verbose_name='registrado por (nome)')),
                ('registrado_em', models.DateTimeField(auto_now_add=True, verbose_name='registrado em')),
                ('cotacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precos_registrados', to='cotador.cotacao', verbose_name='cotação')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos', to='fornecedores.fornecedor', verbose_name='fornecedor')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos', to='produtos.modelo', verbose_name='modelo')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
            ],
            options={
                'verbose_name': 'preço de fornecedor',
                'verbose_name_plural': 'tabela de preços',
                'ordering': ['-registrado_em', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='fabricante',
            constraint=models.UniqueConstraint(fields=('nome_normalizado',), name='fabricante_nome_unico'),
        ),
        migrations.AddConstraint(
            model_name='marca',
            constraint=models.UniqueConstraint(fields=('fabricante', 'nome_normalizado'), name='marca_nome_unico_no_fabricante'),
        ),
        migrations.AddConstraint(
            model_name='modelo',
            constraint=models.UniqueConstraint(fields=('marca', 'nome_normalizado'), name='modelo_nome_unico_na_marca'),
        ),
        migrations.AddIndex(
            model_name='precofornecedor',
            index=models.Index(fields=['fornecedor', 'modelo', '-registrado_em'], name='produtos_pr_fornece_da9247_idx'),
        ),
    ]
