# Generated by Django 6.0.8 on 2026-08-31 04:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedores', '0001_initial'),
        ('licitacoes', '0002_cotacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='Como a equipe chama esta cotação. Vazio = usa o objeto do edital.', max_length=255, verbose_name='título')),
                ('transporte', models.DecimalField(decimal_places=2, default=Decimal('8'), max_digits=6, verbose_name='transporte (% do custo)')),
                ('garantia', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='garantia extra (% do custo)')),
                ('lucro_minimo', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=6, verbose_name='lucro mínimo (% do custo)')),
                ('lucro_maximo', models.DecimalField(decimal_places=2, default=Decimal('35'), max_digits=6, verbose_name='lucro máximo (% do custo)')),
                ('impostos', models.DecimalField(decimal_places=2, default=Decimal('10'), help_text='ICMS/Simples + PIS + COFINS + IPI + ISS somados.', max_digits=6, verbose_name='tributos (% da venda)')),
                ('valor_cotado', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='valor cotado')),
                ('preco_reserva', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='preço de reserva')),
                ('lucro_total', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='lucro')),
                ('capital', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='capital necessário')),
                ('impostos_embutidos', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='impostos embutidos')),
                ('custo_produtos', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='custo dos produtos')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('atualizada_em', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('atualizada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotacoes_atualizadas', to=settings.AUTH_USER_MODEL, verbose_name='atualizada por')),
                ('criada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotacoes_criadas', to=settings.AUTH_USER_MODEL, verbose_name='criada por')),
                ('oportunidade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cotacao_cotador', to='licitacoes.oportunidadesalva', verbose_name='oportunidade salva')),
            ],
            options={
                'verbose_name': 'cotação',
                'verbose_name_plural': 'cotações',
                'ordering': ['-atualizada_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemCotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('numero_item', models.CharField(blank=True, max_length=20, verbose_name='nº do item no edital')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('unidade', models.CharField(blank=True, max_length=40, verbose_name='unidade de medida')),
                ('quantidade', models.DecimalField(decimal_places=4, default=0, max_digits=16, verbose_name='quantidade')),
                ('valor_referencia', models.DecimalField(blank=True, decimal_places=4, help_text='O estimado do edital — base do desconto mostrado na planilha.', max_digits=16, null=True, verbose_name='valor unitário de referência')),
                ('margem_minima', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='margem mínima (%)')),
                ('margem_maxima', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='margem máxima (%)')),
                ('impostos', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='tributos próprios (% da venda)')),
                ('cotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='cotador.cotacao', verbose_name='cotação')),
            ],
            options={
                'verbose_name': 'item da cotação',
                'verbose_name_plural': 'itens da cotação',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OfertaFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Preservado para a cotação sobreviver à exclusão do cadastro.', max_length=255, verbose_name='fornecedor (snapshot)')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('custo_produto', models.DecimalField(decimal_places=4, default=0, max_digits=16, verbose_name='custo do produto (un.)')),
                ('frete', models.DecimalField(decimal_places=4, default=0, max_digits=16, verbose_name='frete (un.)')),
                ('outros', models.DecimalField(decimal_places=4, default=0, max_digits=16, verbose_name='outros custos (un.)')),
                ('escolhida', models.BooleanField(default=False, help_text='A oferta que entra no cálculo. No máximo uma por item.', verbose_name='escolhida')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofertas', to='fornecedores.fornecedor', verbose_name='fornecedor')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='cotador.itemcotacao', verbose_name='item')),
            ],
            options={
                'verbose_name': 'oferta de fornecedor',
                'verbose_name_plural': 'ofertas de fornecedor',
                'ordering': ['ordem', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('escolhida', True)), fields=('item',), name='cotador_uma_oferta_escolhida_por_item')],
            },
        ),
    ]
