# Generated by Django 6.0.8 on 2026-09-27 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotador', '0002_markup'),
        ('licitacoes', '0003_delete_cotacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='oportunidade',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cotacao', to='licitacoes.oportunidadesalva', verbose_name='oportunidade salva'),
        ),
    ]
