# Generated by Django 6.0.8 on 2026-09-27 02:56

from django.db import migrations, models

from apps.accounts.autoria import preencher_nomes_existentes


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_superusuario_substitui_staff"),
        ('cotador', '0003_alter_cotacao_oportunidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='atualizada_por_nome',
            field=models.CharField(blank=True, help_text='Gravado junto com o autor: o nome continua aqui se o usuário for excluído.', max_length=150, verbose_name='atualizada por (nome)'),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='criada_por_nome',
            field=models.CharField(blank=True, help_text='Gravado junto com o autor: o nome continua aqui se o usuário for excluído.', max_length=150, verbose_name='criada por (nome)'),
        ),
        preencher_nomes_existentes(("cotador", "Cotacao", ["criada_por", "atualizada_por"])),
    ]
