# Generated by Django 6.0.8 on 2026-10-04 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotador', '0004_nome_do_autor'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertafornecedor',
            name='fabricante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofertas', to='produtos.fabricante', verbose_name='fabricante'),
        ),
        migrations.AddField(
            model_name='ofertafornecedor',
            name='fabricante_nome',
            field=models.CharField(blank=True, max_length=150, verbose_name='fabricante (snapshot)'),
        ),
        migrations.AddField(
            model_name='ofertafornecedor',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofertas', to='produtos.marca', verbose_name='marca'),
        ),
        migrations.AddField(
            model_name='ofertafornecedor',
            name='marca_nome',
            field=models.CharField(blank=True, max_length=150, verbose_name='marca (snapshot)'),
        ),
        migrations.AddField(
            model_name='ofertafornecedor',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofertas', to='produtos.modelo', verbose_name='modelo'),
        ),
        migrations.AddField(
            model_name='ofertafornecedor',
            name='modelo_nome',
            field=models.CharField(blank=True, max_length=150, verbose_name='modelo (snapshot)'),
        ),
    ]
