# Generated by Django 6.0.8 on 2026-08-29 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OportunidadeSalva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_orgao', models.CharField(max_length=20, verbose_name='CNPJ do órgão')),
                ('ano_compra', models.CharField(max_length=8, verbose_name='ano da compra')),
                ('sequencial_compra', models.CharField(max_length=20, verbose_name='sequencial da compra')),
                ('objeto', models.TextField(blank=True, verbose_name='objeto')),
                ('orgao_nome', models.CharField(blank=True, max_length=255, verbose_name='órgão')),
                ('uasg', models.CharField(blank=True, max_length=20, verbose_name='UASG')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('municipio', models.CharField(blank=True, max_length=255, verbose_name='município')),
                ('modalidade', models.CharField(blank=True, max_length=120, verbose_name='modalidade')),
                ('situacao', models.CharField(blank=True, max_length=120, verbose_name='situação')),
                ('data_publicacao', models.DateField(blank=True, null=True, verbose_name='publicada em')),
                ('data_encerramento_proposta', models.DateField(blank=True, help_text="Base do status 'expirada'.", null=True, verbose_name='propostas até')),
                ('valor_total_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='valor estimado')),
                ('plataforma_id', models.CharField(blank=True, help_text='Id do registro em apps/integracoes/plataformas.py.', max_length=40, verbose_name='plataforma')),
                ('plataforma_nome', models.CharField(blank=True, max_length=120, verbose_name='nome da plataforma')),
                ('link_plataforma', models.TextField(blank=True, verbose_name='link na plataforma')),
                ('link_pncp', models.TextField(blank=True, verbose_name='link no PNCP')),
                ('capag', models.JSONField(blank=True, null=True, verbose_name='selo CAPAG')),
                ('itens', models.JSONField(default=list, help_text='As linhas da busca deste edital, no formato de OportunidadeSerializer.', verbose_name='itens (snapshot)')),
                ('texto_busca', models.TextField(blank=True, verbose_name='texto de busca')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='salva em')),
                ('removida_em', models.DateTimeField(blank=True, null=True, verbose_name='removida em')),
                ('removida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades_removidas', to=settings.AUTH_USER_MODEL, verbose_name='removida por')),
                ('salva_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades_salvas', to=settings.AUTH_USER_MODEL, verbose_name='salva por')),
            ],
            options={
                'verbose_name': 'oportunidade salva',
                'verbose_name_plural': 'oportunidades salvas',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='EventoOportunidadeSalva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('salva', 'Oportunidade salva'), ('prazo_vencido', 'Prazo de proposta encerrado'), ('removida', 'Removida da lista'), ('proposta_gerada', 'Proposta gerada')], max_length=32, verbose_name='tipo')),
                ('descricao', models.TextField(help_text='Texto pronto para exibição no histórico.', verbose_name='descrição')),
                ('dados', models.JSONField(blank=True, default=dict, verbose_name='dados')),
                ('ocorrido_em', models.DateTimeField(auto_now_add=True, verbose_name='ocorrido em')),
                ('autor', models.ForeignKey(blank=True, help_text='Nulo = evento do sistema (ex.: prazo vencido).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_de_oportunidade', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('oportunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='licitacoes.oportunidadesalva', verbose_name='oportunidade')),
            ],
            options={
                'verbose_name': 'evento de oportunidade salva',
                'verbose_name_plural': 'eventos de oportunidade salva',
                'ordering': ['ocorrido_em', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='oportunidadesalva',
            constraint=models.UniqueConstraint(condition=models.Q(('removida_em__isnull', True)), fields=('cnpj_orgao', 'ano_compra', 'sequencial_compra'), name='oportunidade_salva_unica_por_compra_ativa'),
        ),
    ]
