# Generated by Django 6.0.8 on 2026-08-29 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licitacoes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cotacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parametros",
                    models.JSONField(default=dict, verbose_name="percentuais"),
                ),
                ("itens", models.JSONField(default=list, verbose_name="itens cotados")),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="valor total cotado",
                    ),
                ),
                (
                    "lucro_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="lucro total",
                    ),
                ),
                (
                    "criada_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criada em"),
                ),
                (
                    "atualizada_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizada em"),
                ),
                (
                    "atualizada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cotacoes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="atualizada por",
                    ),
                ),
                (
                    "oportunidade",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cotacao",
                        to="licitacoes.oportunidadesalva",
                        verbose_name="oportunidade salva",
                    ),
                ),
            ],
            options={
                "verbose_name": "cotação",
                "verbose_name_plural": "cotações",
                "ordering": ["-atualizada_em"],
            },
        ),
    ]
