# Generated by Django 6.0.8 on 2026-09-27 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licitacoes', '0002_cotacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cotacao',
        ),
    ]
