# Generated by Django 6.0.8 on 2026-09-27 02:56

from django.db import migrations, models

from apps.accounts.autoria import preencher_nomes_existentes


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_superusuario_substitui_staff"),
        ('licitacoes', '0003_delete_cotacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventooportunidadesalva',
            name='autor_nome',
            field=models.CharField(blank=True, help_text='Gravado junto com o autor: o nome continua aqui se o usuário for excluído.', max_length=150, verbose_name='autor (nome)'),
        ),
        migrations.AddField(
            model_name='oportunidadesalva',
            name='removida_por_nome',
            field=models.CharField(blank=True, help_text='Gravado junto com o autor: o nome continua aqui se o usuário for excluído.', max_length=150, verbose_name='removida por (nome)'),
        ),
        migrations.AddField(
            model_name='oportunidadesalva',
            name='salva_por_nome',
            field=models.CharField(blank=True, help_text='Gravado junto com o autor: o nome continua aqui se o usuário for excluído.', max_length=150, verbose_name='salva por (nome)'),
        ),
        preencher_nomes_existentes(("licitacoes", "OportunidadeSalva", ["salva_por", "removida_por"]), ("licitacoes", "EventoOportunidadeSalva", ["autor"])),
    ]
