# Generated by Django 6.0.8 on 2026-10-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacoes', '0004_nome_do_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventooportunidadesalva',
            name='tipo',
            field=models.CharField(choices=[('salva', 'Oportunidade salva'), ('prazo_vencido', 'Prazo de proposta encerrado'), ('removida', 'Removida da lista'), ('proposta_gerada', 'Cotação salva'), ('proposta', 'Proposta gerada')], max_length=32, verbose_name='tipo'),
        ),
    ]
