# Generated by Django 6.0.8 on 2026-10-05 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licitacoes', '0005_alter_eventooportunidadesalva_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, help_text='O valor cotado no momento de gerar.', max_digits=16, verbose_name='valor proposto')),
                ('gerada_por_nome', models.CharField(blank=True, max_length=150, verbose_name='gerada por (nome)')),
                ('gerada_em', models.DateTimeField(auto_now_add=True, verbose_name='gerada em')),
                ('gerada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas_geradas', to=settings.AUTH_USER_MODEL, verbose_name='gerada por')),
                ('oportunidade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposta', to='licitacoes.oportunidadesalva', verbose_name='oportunidade salva')),
            ],
            options={
                'verbose_name': 'proposta',
                'verbose_name_plural': 'propostas',
            },
        ),
    ]
