# Generated by Django 6.0.8 on 2026-10-05 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_nome_do_autor'),
        ('propostas', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='O CNPJ com que se disputa. Nulo até escolher (com uma empresa só, é ela).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propostas', to='empresas.empresa', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='validade_dias',
            field=models.PositiveIntegerField(default=60, help_text='60 é o mínimo que a maioria dos editais exige.', verbose_name='validade da proposta (dias)'),
        ),
        migrations.CreateModel(
            name='ArquivoProposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('gerado', 'Gerado pelo sistema'), ('subido', 'Enviado pela equipe')], max_length=8, verbose_name='origem')),
                ('arquivo', models.CharField(max_length=500, verbose_name='arquivo (chave no armazenamento)')),
                ('nome_original', models.CharField(max_length=255, verbose_name='nome')),
                ('tamanho', models.PositiveBigIntegerField(default=0, verbose_name='tamanho (bytes)')),
                ('content_type', models.CharField(blank=True, max_length=120, verbose_name='tipo')),
                ('enviado_por_nome', models.CharField(blank=True, max_length=150, verbose_name='enviado por')),
                ('enviado_em', models.DateTimeField(auto_now_add=True, verbose_name='enviado em')),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='propostas.proposta', verbose_name='proposta')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arquivos_proposta', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'arquivo da proposta',
                'verbose_name_plural': 'arquivos da proposta',
                'ordering': ['origem', 'enviado_em', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ModeloProposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.CharField(max_length=500, verbose_name='arquivo (chave no armazenamento)')),
                ('nome_original', models.CharField(max_length=255, verbose_name='nome original')),
                ('enviado_por_nome', models.CharField(blank=True, max_length=150, verbose_name='enviado por')),
                ('enviado_em', models.DateTimeField(auto_now=True, verbose_name='enviado em')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='modelo_proposta', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'modelo de proposta',
                'verbose_name_plural': 'modelos de proposta',
            },
        ),
    ]
