# Generated by Django 6.0.8 on 2026-08-31 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='razão social')),
                ('fantasia', models.CharField(blank=True, max_length=255, verbose_name='nome fantasia')),
                ('tipo', models.CharField(choices=[('pj', 'Pessoa jurídica'), ('pf', 'Pessoa física'), ('mei', 'MEI')], default='pj', max_length=8, verbose_name='tipo')),
                ('cnpj', models.CharField(help_text='Só dígitos — a máscara é da tela (ver documentos.py).', max_length=14, unique=True, verbose_name='CNPJ / CPF')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=40, verbose_name='inscrição estadual')),
                ('categoria', models.CharField(choices=[('materiais', 'Materiais'), ('equipamentos', 'Equipamentos'), ('servicos', 'Serviços'), ('logistica', 'Logística'), ('tecnologia', 'Tecnologia')], default='materiais', max_length=20, verbose_name='categoria')),
                ('cep', models.CharField(blank=True, max_length=8, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=255, verbose_name='logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('complemento', models.CharField(blank=True, max_length=120, verbose_name='complemento')),
                ('bairro', models.CharField(blank=True, max_length=120, verbose_name='bairro')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('cidade', models.CharField(blank=True, max_length=120, verbose_name='cidade')),
                ('responsavel', models.CharField(blank=True, max_length=150, verbose_name='responsável')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('celular', models.CharField(blank=True, max_length=20, verbose_name='celular / WhatsApp')),
                ('condicao_pagamento', models.CharField(choices=[('a_vista', 'À vista'), ('7_dias', '7 dias'), ('14_28_dias', '14/28 dias'), ('30_dias', '30 dias'), ('30_60_90_dias', '30/60/90 dias')], default='30_dias', max_length=20, verbose_name='condição de pagamento')),
                ('prazo_entrega_dias', models.PositiveIntegerField(blank=True, null=True, verbose_name='prazo de entrega (dias)')),
                ('dados_bancarios', models.CharField(blank=True, max_length=120, verbose_name='banco / agência / conta')),
                ('chave_pix', models.CharField(blank=True, max_length=140, verbose_name='chave PIX')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('situacao', models.CharField(choices=[('ativo', 'Ativo'), ('em_analise', 'Em análise'), ('inativo', 'Inativo'), ('documentacao_vencida', 'Documentação vencida')], default='ativo', max_length=24, verbose_name='situação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='cadastrado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fornecedores_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='cadastrado por')),
            ],
            options={
                'verbose_name': 'fornecedor',
                'verbose_name_plural': 'fornecedores',
                'ordering': ['nome'],
            },
        ),
    ]
