# Generated by Django 6.0.8 on 2026-08-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCapag',
            fields=[
                ('uf', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nota', models.CharField(max_length=2)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado (CAPAG)',
                'verbose_name_plural': 'Estados (CAPAG)',
                'ordering': ['uf'],
            },
        ),
        migrations.CreateModel(
            name='MunicipioCapag',
            fields=[
                ('codigo_ibge', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_municipio', models.CharField(max_length=255)),
                ('uf', models.CharField(max_length=2)),
                ('nota', models.CharField(max_length=2)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Município (CAPAG)',
                'verbose_name_plural': 'Municípios (CAPAG)',
                'ordering': ['nome_municipio'],
            },
        ),
    ]
