# Generated by Django 6.0.8 on 2026-09-20 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigArmazenamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(help_text='Chave do driver instalado (ver apps/armazenamento/registro.py).', max_length=40, verbose_name='driver')),
                ('opcoes', models.JSONField(blank=True, default=dict, help_text='Os campos não secretos do driver escolhido — bucket, endpoint, região.', verbose_name='opções')),
                ('segredos_cifrados', models.TextField(blank=True, verbose_name='segredos')),
                ('segredos_definidos_em', models.DateTimeField(blank=True, null=True, verbose_name='segredos definidos em')),
                ('testado_em', models.DateTimeField(blank=True, null=True, verbose_name='testado com sucesso em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configs_armazenamento', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='config_armazenamento', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'configuração de armazenamento',
                'verbose_name_plural': 'configurações de armazenamento',
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='armazenamento_um_por_tenant')],
            },
        ),
    ]
