# Generated by Django 6.0.8 on 2026-09-20 19:37

from django.db import migrations, models

from apps.tenants.models import TENANT_PADRAO_NOME, TENANT_PADRAO_SLUG


def criar_tenant_inicial(apps, schema_editor):
    """A única linha da tabela. Nasce aqui, e não por um comando que alguém
    precisa lembrar de rodar, porque tudo que é criado a partir de agora tem
    FK obrigatória para ela — um banco migrado sem este registro não
    conseguiria gravar nem a primeira empresa."""

    Tenant = apps.get_model("tenants", "Tenant")
    Tenant.objects.get_or_create(
        slug=TENANT_PADRAO_SLUG, defaults={"nome": TENANT_PADRAO_NOME}
    )


def remover_tenant_inicial(apps, schema_editor):
    Tenant = apps.get_model("tenants", "Tenant")
    Tenant.objects.filter(slug=TENANT_PADRAO_SLUG).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('slug', models.SlugField(help_text='Usado no caminho dos arquivos no bucket — mudar quebra o que já foi gravado.', max_length=60, unique=True, verbose_name='identificador')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'tenant',
                'verbose_name_plural': 'tenants',
                'ordering': ['nome'],
            },
        ),
        migrations.RunPython(criar_tenant_inicial, remover_tenant_inicial),
    ]
