# Generated by Django 6.0.8 on 2026-09-20 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# O catálogo que toda empresa precisa, na ordem em que os editais pedem. Os
# links são o ponto de partida do alerta de vencimento ("renovar agora") —
# ficam em campo, e não no código, porque site de órgão muda. Estadual e
# municipal não têm link: dependem da UF e do município da empresa.
CATALOGO = [
    # (bloco, nome, órgão, exige_validade, obrigatorio, link, ordem)
    ("juridica", "Contrato social consolidado", "Junta Comercial", False, True, "", 10),
    ("juridica", "Certidão simplificada da Junta Comercial", "Junta Comercial", True, False, "", 20),
    (
        "fiscal",
        "CND de tributos federais e dívida ativa",
        "Receita Federal / PGFN — conjunta",
        True,
        True,
        "https://servicos.receita.fazenda.gov.br/",
        10,
    ),
    (
        "fiscal",
        "Certificado de Regularidade do FGTS (CRF)",
        "Caixa Econômica Federal",
        True,
        True,
        "https://consulta-crf.caixa.gov.br/",
        20,
    ),
    (
        "fiscal",
        "Certidão negativa de débitos trabalhistas (CNDT)",
        "Tribunal Superior do Trabalho",
        True,
        True,
        "https://cndt-certidao.tst.jus.br/",
        30,
    ),
    ("fiscal", "Certidão de regularidade estadual", "Secretaria da Fazenda do estado", True, True, "", 40),
    ("fiscal", "Certidão de tributos municipais", "Prefeitura da sede", True, True, "", 50),
    ("economica", "Balanço patrimonial e DRE", "Exercício encerrado", False, True, "", 10),
    (
        "economica",
        "Certidão negativa de falência e recuperação judicial",
        "Distribuidor cível do TJ",
        True,
        True,
        "",
        20,
    ),
    ("tecnica", "Atestado de capacidade técnica", "Cliente atendido", False, True, "", 10),
    ("tecnica", "Registro em entidade profissional", "CREA, CRM, CRF…", True, False, "", 20),
    (
        "outros",
        "Outro documento",
        "",
        True,
        False,
        "",
        99,
    ),
]


def semear_catalogo(apps, schema_editor):
    """`tenant` nulo: é o catálogo padrão, o mesmo para todo cliente. O que
    um cliente acrescentar depois nasce com o tenant dele."""

    TipoDocumento = apps.get_model("documentos", "TipoDocumento")
    for bloco, nome, orgao, validade, obrigatorio, link, ordem in CATALOGO:
        TipoDocumento.objects.get_or_create(
            tenant=None,
            nome=nome,
            defaults={
                "bloco": bloco,
                "orgao_emissor": orgao,
                "exige_validade": validade,
                "obrigatorio": obrigatorio,
                "link_emissor": link,
                "ordem": ordem,
            },
        )


def remover_catalogo(apps, schema_editor):
    TipoDocumento = apps.get_model("documentos", "TipoDocumento")
    TipoDocumento.objects.filter(tenant=None, nome__in=[linha[1] for linha in CATALOGO]).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='Só para o tipo livre ("outro documento"): é o que distingue dois deles.', max_length=160, verbose_name='título')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('arquivado_em', models.DateTimeField(blank=True, null=True, verbose_name='arquivado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='empresas.empresa', verbose_name='empresa')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['tipo__bloco', 'tipo__ordem', 'tipo__nome'],
            },
        ),
        migrations.CreateModel(
            name='EventoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('enviado', 'Enviado'), ('renovado', 'Renovado'), ('baixado', 'Baixado'), ('arquivado', 'Arquivado'), ('restaurado', 'Restaurado')], max_length=12, verbose_name='evento')),
                ('detalhe', models.CharField(blank=True, max_length=240, verbose_name='detalhe')),
                ('quando', models.DateTimeField(auto_now_add=True, verbose_name='quando')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_documento', to=settings.AUTH_USER_MODEL, verbose_name='quem')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='documentos.documento', verbose_name='documento')),
            ],
            options={
                'verbose_name': 'evento do documento',
                'verbose_name_plural': 'eventos do documento',
                'ordering': ['-quando'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloco', models.CharField(choices=[('juridica', 'Habilitação jurídica'), ('fiscal', 'Fiscal, social e trabalhista'), ('economica', 'Econômico-financeira'), ('tecnica', 'Técnica'), ('outros', 'Outros')], max_length=12, verbose_name='bloco')),
                ('nome', models.CharField(max_length=160, verbose_name='nome')),
                ('orgao_emissor', models.CharField(blank=True, max_length=160, verbose_name='órgão emissor')),
                ('exige_validade', models.BooleanField(default=True, help_text='Contrato social e atestado não vencem — não podem entrar na conta de vencidos.', verbose_name='exige validade')),
                ('obrigatorio', models.BooleanField(default=True, help_text='Abre a vaga automaticamente para toda empresa nova.', verbose_name='obrigatório')),
                ('link_emissor', models.URLField(blank=True, help_text='Para onde o alerta de vencimento manda quem precisa renovar.', verbose_name='site do emissor')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('tenant', models.ForeignKey(blank=True, help_text='Vazio = catálogo padrão, comum a todos.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_documento', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'tipo de documento',
                'verbose_name_plural': 'tipos de documento',
                'ordering': ['bloco', 'ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='documentos.tipodocumento', verbose_name='tipo'),
        ),
        migrations.CreateModel(
            name='VersaoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.PositiveIntegerField(verbose_name='versão')),
                ('numero', models.CharField(blank=True, max_length=80, verbose_name='número do documento')),
                ('emissao', models.DateField(blank=True, null=True, verbose_name='emissão')),
                ('validade', models.DateField(blank=True, null=True, verbose_name='validade')),
                ('arquivo', models.CharField(max_length=500, verbose_name='caminho no armazenamento')),
                ('nome_original', models.CharField(max_length=255, verbose_name='nome do arquivo enviado')),
                ('tamanho', models.PositiveIntegerField(verbose_name='tamanho (bytes)')),
                ('content_type', models.CharField(blank=True, max_length=120, verbose_name='tipo do arquivo')),
                ('hash_sha256', models.CharField(blank=True, help_text='Para provar que o arquivo baixado é o mesmo que foi enviado.', max_length=64, verbose_name='hash')),
                ('nota', models.CharField(blank=True, help_text='O que mudou ("renovação de agosto") — aparece no histórico.', max_length=200, verbose_name='nota da versão')),
                ('enviado_em', models.DateTimeField(auto_now_add=True, verbose_name='enviado em')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes', to='documentos.documento', verbose_name='documento')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versoes_documento_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
            ],
            options={
                'verbose_name': 'versão do documento',
                'verbose_name_plural': 'versões do documento',
                'ordering': ['-versao'],
            },
        ),
        migrations.AddConstraint(
            model_name='tipodocumento',
            constraint=models.UniqueConstraint(fields=('tenant', 'nome'), name='tipo_documento_nome_unico_por_tenant'),
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.UniqueConstraint(fields=('empresa', 'tipo', 'titulo'), name='documento_unico_por_empresa_e_tipo'),
        ),
        migrations.AddConstraint(
            model_name='versaodocumento',
            constraint=models.UniqueConstraint(fields=('documento', 'versao'), name='versao_unica_por_documento'),
        ),
        migrations.RunPython(semear_catalogo, remover_catalogo),
    ]
