# Generated by Django 6.0.8 on 2026-09-27 02:56

from django.db import migrations, models

from apps.accounts.autoria import preencher_nomes_existentes


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_superusuario_substitui_staff"),
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventodocumento',
            name='autor_nome',
            field=models.CharField(blank=True, help_text='Gravado junto com o autor: o nome continua aqui se o usuário for excluído.', max_length=150, verbose_name='quem (nome)'),
        ),
        migrations.AddField(
            model_name='versaodocumento',
            name='enviado_por_nome',
            field=models.CharField(blank=True, help_text='Gravado junto com o autor: o nome continua aqui se o usuário for excluído.', max_length=150, verbose_name='enviado por (nome)'),
        ),
        preencher_nomes_existentes(("documentos", "VersaoDocumento", ["enviado_por"]), ("documentos", "EventoDocumento", ["autor"])),
    ]
